# Site settings
title: Rushi Patel's personal Github Portfolio
description: Rushi Patel's personal Github Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rushi Patel
user_description: I am a Computer Engineering student at the University of Texas at Austin. Currently I am seeking an internship in the field of software engineering. I will complete a Bachelor's Degree in Electrical and Computer Engineering by Fall 2022 with a specialization in Software Engineering and Design.
user_title: Computer Engineering Student
email: rpatel1@utexas.edu
twitter_username: rushiipatel
github_username:  rpatel1023.github.io
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
